import './globals.css'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'

const applimincho = localFont({
  src: './AppliMincho.otf',
  display: 'swap'
})

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={applimincho.className}>{children}</body>
    </html>
  )
}
